name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout docs site repo
        uses: actions/checkout@v2
        with:
          repository: gdereese/gdereese.github.io
          path: docs

      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install package
        run: |
          poetry install

      - name: Lint
        run: |
          poetry run pylint --rcfile .pylintrc src/tonescript

      - name: Test
        run: |
          poetry run pytest
