name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install package
        run: |
          poetry install

      - name: Lint
        run: |
          poetry run pylint --rcfile .pylintrc src/tonescript

      - name: Test
        run: |
          poetry run pytest

      - name: Build
        run: |
          poetry run build

      - name: Build HTML docs
        run: |
          poetry run pdoc --template-dir docs --html tonescript
