name: Publish

on:
  push:
    tags:
      - \d+\.\d+\.\d+
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Build package
        run: |
          poetry build

      - name: Publish package
        run: |
          poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
